//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSanGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaCTHD { get; set; }
        public int MaHD { get; set; }
        public int MaSanGo { get; set; }
        public int SoLuongMua { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanGo SanGo { get; set; }
    }
}
