//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSanGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public int MaCV { get; set; }
        public string MatKhau { get; set; }
        public string SDT { get; set; }
        public string SoCCCD { get; set; }
        public string Email { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
    }
}
